Allow build configurations in dockerfile
MathHubInfo/mhd pull request #96
Opened 2022-07-14 13:17 UTC by jO-Osko

2022-07-14 15:42 UTC, tkw1536 requested changes

2022-07-14 15:42 UTC, tkw1536 commented on Dockerfile
> +ENV DJANGO_DB_ENGINE "django.db.backends.sqlite3"
Shouldn't these be `ARG` also?

2022-07-27 13:44 UTC, jO-Osko commented on Dockerfile
> +ENV DJANGO_DB_ENGINE "django.db.backends.sqlite3"
Yes, fixed

2022-07-28 17:41 UTC, tkw1536 commented on Dockerfile
> +ENV DJANGO_DB_ENGINE "django.db.backends.sqlite3"
LGTM

2022-07-28 17:42 UTC, merged